jobs:
  - name: ingest_discharge_and_inference
    interval_minutes: 10

  - name: ingest_precip_forecast
    interval_minutes: 10

  - name: ingest_precip_observation
    interval_minutes: 10
  
  - name: ingest_precip_hourly_observation
    interval_minutes: 10